spring:
  datasource:
    url: jdbc:h2:./shorty-db;DB_CLOSE_ON_EXIT=FALSE
    username: shorty
    password: shorty,02
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

meta:
  domain: http://localhost:8080